---

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

extends:
  - airbnb-base

rules:
  no-console: 0

- name: Run ESLint
  uses: stefanoeb/eslint-action@1.0.2
